# SPDX-FileCopyrightText: None
# SPDX-License-Identifier: CC0-1.0

Dependencies:
  - 'on': ['@all']
    'require':
      'frameworks/extra-cmake-modules': '@latest-kf6'
      'frameworks/kcmutils': '@latest-kf6'
      'frameworks/kconfig': '@latest-kf6'
      'frameworks/kcoreaddons': '@latest-kf6'
      'frameworks/ki18n': '@latest-kf6'
      'third-party/libsnapd-qt-2-1-devel': '@latest'

Options:
  require-passing-tests-on: ['@all']
  clang-format-versions: [19]
