# SPDX-FileCopyrightText: 2024 Soumyadeep Ghosh <soumyadghosh@ubuntu.com>
# SPDX-License-Identifier: GPL-2.0-or-later
version = 1

[[annotations]]
path = "debian/**"
SPDX-FileCopyrightText = "2024 Soumyadeep Ghosh <soumyadghosh@ubuntu.com>"
SPDX-FileContributor = "Alex Lowe"
SPDX-License-Identifier = "GPL-2.0-or-later"