# SPDX-FileCopyrightText: 2025 Soumyadeep Ghosh <soumyadghosh@ubuntu.com>
# SPDX-License-Identifier: GPL-2.0-or-later

name: snap-kcm
base: core22
version: '0.1'
summary: KDE Configuration Module to manage permissions of snap packages
description: |
  KDE Configuration Module to manage permissions of snap packages build on the snapd-glib api.
  Snapped to be used as a standalone app, but KCMs are not meant to be used that way, please use with caution
license: GPL-2.0-OR-LATER
source-code: https://invent.kde.org/soumyadghosh/snap-kcm
issues: https://invent.kde.org/soumyadghosh/snap-kcm/issues
contact: soumyadghosh+snap-kcm@ubuntu.com
donation: https://github.com/sponsors/soumyaDghosh
grade: stable
confinement: strict

package-repositories:
  - type: apt
    components:
      - main
    suites:
      - jammy
    key-id: 444DABCF3667D0283F894EDDE6D4736255751E5D
    url: http://origin.archive.neon.kde.org/user
    key-server: keyserver.ubuntu.com

parts:
  # snapd-glib-api:
  #   source: https://github.com/canonical/snapd-glib.git
  #   source-tag: '1.66'
  #   source-depth: 1
  #   plugin: meson
  #   build-environment:
  #     - PKG_CONFIG_PATH: /snap/kde-qt6-core22-sdk/current/usr/lib/x86_64-linux-gnu/pkgconfig:/snap/kf6-core22-sdk/current/usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/pkgconfig:/usr/lib/pkgconfig:/usr/lib/${CRAFT_ARCH_TRIPLET_BUILD_FOR}/pkgconfig
  #   meson-parameters:
  #     - --prefix=/usr
  #     - -Dintrospection=false
  #     - -Ddocs=false
  #     - -Dvala-bindings=false
  #     - -Dexamples=false
  #     - -Dtests=false
  #   build-packages:
  #     - meson
  #     - libglib2.0-dev
  #     - libsoup-3.0-dev
  #     - qtchooser

  snap-kcm:
    source: https://invent.kde.org/soumyadghosh/snap-kcm.git
    source-depth: 1
    plugin: cmake
    build-environment:
      - PKG_CONFIG_PATH: ${CRAFT_STAGE}/usr/lib/$CRAFT_ARCH_TRIPLET_BUILD_FOR/pkgconfig
    override-pull: |
      craftctl default
    cmake-parameters:
      - -DCMAKE_INSTALL_PREFIX=/usr
    override-build: |
      craftctl default
      sed -i '3d' ${CRAFT_PART_INSTALL}/usr/share/applications/kcm_snap.desktop
    build-packages:
      - libsnapd-glib-dev
      - libsnapd-qt-dev
  deps:
    plugin: nil
    stage-packages:
      - libsoup-3.0-0
      - libjson-glib-1.0-0
      - libsnapd-glib1
      - libsnapd-qt1
    prime:
      - usr/lib/x86_64-linux-gnu/libsoup-3.0*
      - usr/lib/x86_64-linux-gnu/libjson-glib-1.0*
      - usr/lib/x86_64-linux-gnu/libsnapd-glib.so.1*
      - usr/lib/x86_64-linux-gnu/libsnapd-qt.so.1*
apps:
  snap-kcm:
    command: usr/bin/kcmshell6 kcm_snap
    extensions: [kde-neon-6]
    environment:
      XDG_CONFIG_DIRS: $SNAP_REAL_HOME/.config:$XDG_CONFIG_DIRS
    desktop: usr/share/applications/kcm_snap.desktop
    plugs:
      - desktop-launch
      - snapd-control
